/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    FinanceTable: typeof import('./components/UI/tables/FinanceTable.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAssetActions: typeof import('./components/assets/TheAssetActions.vue')['default']
    TheAssetChart: typeof import('./components/assets/TheAssetChart.vue')['default']
    TheAssetDetails: typeof import('./components/assets/TheUserAsset.vue')['default']
    TheAssetInfo: typeof import('./components/assets/TheAssetInfo.vue')['default']
    TheUserAsset: typeof import('./components/assets/TheUserAsset.vue')['default']
    TheUserAssetAction: typeof import('./components/user/TheUserAssetAction.vue')['default']
    TheUserAssetInfo: typeof import('./components/user/TheUserAssetInfo.vue')['default']
    TheUserBalance: typeof import('./components/user/TheUserBalance.vue')['default']
    TheUserTotalBalance: typeof import('./components/user/TheUserTotalBalance.vue')['default']
  }
}
