/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/user/[id]': RouteRecordInfo<'/admin/user/[id]', '/admin/user/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/assets/': RouteRecordInfo<'/assets/', '/assets', Record<never, never>, Record<never, never>>,
    '/assets/[id]': RouteRecordInfo<'/assets/[id]', '/assets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
    '/user/action': RouteRecordInfo<'/user/action', '/user/action', Record<never, never>, Record<never, never>>,
  }
}
